# Generated by Django 5.1.7 on 2025-03-25 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name="Artist",
            new_name="Artists",
        ),
        migrations.RenameModel(
            old_name="Exhibit",
            new_name="Exhibits",
        ),
        migrations.CreateModel(
            name="Reservations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reserve_date", models.DateField()),
                ("status", models.CharField(max_length=20)),
                (
                    "exhibit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hello.exhibits"
                    ),
                ),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hello.visitors"
                    ),
                ),
            ],
        ),
    ]
