# Generated by Django 5.1.7 on 2025-03-26 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0002_visitors_rename_artist_artists_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservations",
            name="exhibit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="hello.exhibits",
            ),
        ),
    ]
